services:
  - type: web
    name: lavender-spirit-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DATABASE_URL
        fromDatabase:
          name: lavender-spirit-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/backend/static/uploads

databases:
  - name: lavender-spirit-db
    databaseName: lavender_spirit
    user: lavender_spirit_user